addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
node_js:
- "4"
- "6"
sudo: false
language: node_js
script: "npm run test"
after_script: "npm i -g codecov.io && cat ./coverage/lcov.info | codecov"
